package bindings

//go:generate ifacemaker -f bridge.go -s AccusationCaller -o iaccusation_caller.go -p bindings -i IAccusationCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s AccusationTransactor -o iaccusation_transactor.go -p bindings -i IAccusationTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s AccusationFilterer -o iaccusation_filterer.go -p bindings -i IAccusationFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IAccusation interface {
	IAccusationCaller
	IAccusationTransactor
	IAccusationFilterer
}

//go:generate ifacemaker -f bridge.go -s CryptoCaller -o icrypto_caller.go -p bindings -i ICryptoCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s CryptoTransactor -o icrypto_transactor.go -p bindings -i ICryptoTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s CryptoFilterer -o icrypto_filterer.go -p bindings -i ICryptoFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type ICrypto interface {
	ICryptoCaller
	ICryptoTransactor
	ICryptoFilterer
}

//go:generate ifacemaker -f bridge.go -s DepositCaller -o ideposit_caller.go -p bindings -i IDepositCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s DepositTransactor -o ideposit_transactor.go -p bindings -i IDepositTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s DepositFilterer -o ideposit_filterer.go -p bindings -i IDepositFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IDeposit interface {
	IDepositCaller
	IDepositTransactor
	IDepositFilterer
}

//go:generate ifacemaker -f bridge.go -s ETHDKGCaller -o iethdkg_caller.go -p bindings -i IEthDkgCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ETHDKGTransactor -o iethdkg_transactor.go -p bindings -i IEthDkgTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ETHDKGFilterer -o iethdkg_filterer.go -p bindings -i IEthDkgFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IEthDkg interface {
	IEthDkgCaller
	IEthDkgTransactor
	IEthDkgFilterer
}

//go:generate ifacemaker -f bridge.go -s GovernorCaller -o igovernor_caller.go -p bindings -i IGovernorCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s GovernorTransactor -o igovernor_transactor.go -p bindings -i IGovernorTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s GovernorFilterer -o igovernor_filterer.go -p bindings -i IGovernorFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IGovernor interface {
	IGovernorCaller
	IGovernorTransactor
	IGovernorFilterer
}

//go:generate ifacemaker -f bridge.go -s ParticipantsCaller -o iparticipants_caller.go -p bindings -i IParticipantsCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ParticipantsTransactor -o iparticipants_transactor.go -p bindings -i IParticipantsTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ParticipantsFilterer -o iparticipants_filterer.go -p bindings -i IParticipantsFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IParticipants interface {
	IParticipantsCaller
	IParticipantsTransactor
	IParticipantsFilterer
}

//go:generate ifacemaker -f bridge.go -s RegistryCaller -o iregistry_caller.go -p bindings -i IRegistryCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s RegistryTransactor -o iregistry_transactor.go -p bindings -i IRegistryTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s RegistryFilterer -o iregistry_filterer.go -p bindings -i IRegistryFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IRegistry interface {
	IRegistryCaller
	IRegistryTransactor
	IRegistryFilterer
}

//go:generate ifacemaker -f bridge.go -s SnapshotsCaller -o isnapshot_caller.go -p bindings -i ISnapshotsCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s SnapshotsTransactor -o isnapshot_transactor.go -p bindings -i ISnapshotsTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s SnapshotsFilterer -o isnapshot_filterer.go -p bindings -i ISnapshotsFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type ISnapshots interface {
	ISnapshotsCaller
	ISnapshotsTransactor
	ISnapshotsFilterer
}

//go:generate ifacemaker -f bridge.go -s StakingCaller -o istaking_caller.go -p bindings -i IStakingCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s StakingTransactor -o istaking_transactor.go -p bindings -i IStakingTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s StakingFilterer -o istaking_filterer.go -p bindings -i IStakingFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IStaking interface {
	IStakingCaller
	IStakingTransactor
	IStakingFilterer
}

//go:generate ifacemaker -f bridge.go -s TokenCaller -o itoken_caller.go -p bindings -i ITokenCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s TokenTransactor -o itoken_transactor.go -p bindings -i ITokenTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s TokenFilterer -o itoken_filterer.go -p bindings -i ITokenFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IToken interface {
	ITokenCaller
	ITokenTransactor
	ITokenFilterer
}

//go:generate ifacemaker -f bridge.go -s ValidatorsCaller -o ivalidators_caller.go -p bindings -i IValidatorsCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ValidatorsTransactor -o ivalidators_transactor.go -p bindings -i IValidatorsTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ValidatorsFilterer -o ivalidators_filterer.go -p bindings -i IValidatorsFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IValidators interface {
	IValidatorsCaller
	IValidatorsTransactor
	IValidatorsFilterer
}
