package bindings

//go:generate ifacemaker -f bridge.go -s ETHDKGCaller -o iface_ethdkg_caller.go -p bindings -i IfaceEthDkgCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ETHDKGTransactor -o iface_ethdkg_transactor.go -p bindings -i IfaceEthDkgTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ETHDKGFilterer -o iface_ethdkg_filterer.go -p bindings -i IfaceEthDkgFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IfaceEthDkg interface {
	IfaceEthDkgCaller
	IfaceEthDkgTransactor
	IfaceEthDkgFilterer
}

//go:generate ifacemaker -f bridge.go -s RegistryCaller -o iface_registry_caller.go -p bindings -i IfaceRegistryCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s RegistryTransactor -o iface_registry_transactor.go -p bindings -i IfaceRegistryTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s RegistryFilterer -o iface_registry_filterer.go -p bindings -i IfaceRegistryFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IfaceRegistry interface {
	IfaceRegistryCaller
	IfaceRegistryTransactor
	IfaceRegistryFilterer
}

//go:generate ifacemaker -f bridge.go -s SnapshotsCaller -o iface_snapshot_caller.go -p bindings -i IfaceSnapshotsCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s SnapshotsTransactor -o iface_snapshot_transactor.go -p bindings -i IfaceSnapshotsTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s SnapshotsFilterer -o iface_snapshot_filterer.go -p bindings -i IfaceSnapshotsFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IfaceSnapshots interface {
	IfaceSnapshotsCaller
	IfaceSnapshotsTransactor
	IfaceSnapshotsFilterer
}

//go:generate ifacemaker -f bridge.go -s ValidatorPoolCaller -o iface_validatorpool_caller.go -p bindings -i IfaceValidatorPoolCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ValidatorPoolTransactor -o iface_validatorpool_transactor.go -p bindings -i IfaceValidatorPoolTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ValidatorPoolFilterer -o iface_validatorpool_filterer.go -p bindings -i IfaceValidatorPoolFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IfaceValidatorPool interface {
	IfaceValidatorPoolCaller
	IfaceValidatorPoolTransactor
	IfaceValidatorPoolFilterer
}

//go:generate ifacemaker -f bridge.go -s MadByteCaller -o iface_madbyte_caller.go -p bindings -i IfaceMadByteCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s MadByteTransactor -o iface_madbyte_transactor.go -p bindings -i IfaceMadByteTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s MadByteFilterer -o iface_madbyte_filterer.go -p bindings -i IfaceMadByteFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IfaceMadByte interface {
	IfaceMadByteCaller
	IfaceMadByteTransactor
	IfaceMadByteFilterer
}

//go:generate ifacemaker -f bridge.go -s StakeNFTCaller -o iface_stake_nft_caller.go -p bindings -i IfaceStakeNFTCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s StakeNFTTransactor -o iface_stake_nft_transactor.go -p bindings -i IfaceStakeNFTTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s StakeNFTFilterer -o iface_stake_nft_filterer.go -p bindings -i IfaceStakeNFTFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IfaceStakeNFT interface {
	IfaceStakeNFTCaller
	IfaceStakeNFTTransactor
	IfaceStakeNFTFilterer
}

//go:generate ifacemaker -f bridge.go -s ValidatorNFTCaller -o iface_validator_nft_caller.go -p bindings -i IfaceValidatorNFTCaller -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ValidatorNFTTransactor -o iface_validator_nft_transactor.go -p bindings -i IfaceValidatorNFTTransactor -c "Generated by ifacemaker. DO NOT EDIT."
//go:generate ifacemaker -f bridge.go -s ValidatorNFTFilterer -o iface_validator_nft_filterer.go -p bindings -i IfaceValidatorNFTFilterer -c "Generated by ifacemaker. DO NOT EDIT."
type IfaceValidatorNFT interface {
	IfaceValidatorNFTCaller
	IfaceValidatorNFTTransactor
	IfaceValidatorNFTFilterer
}
