// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

// IDepositTransactor ...
type IDepositTransactor interface {
	// Deposit is a paid mutator transaction binding the contract method 0xb6b55f25.
	//
	// Solidity: function deposit(uint256 amount) returns(bool)
	Deposit(opts *bind.TransactOpts, amount *big.Int) (*types.Transaction, error)
	// DepositFor is a paid mutator transaction binding the contract method 0x2f4f21e2.
	//
	// Solidity: function depositFor(address who, uint256 amount) returns(bool)
	DepositFor(opts *bind.TransactOpts, who common.Address, amount *big.Int) (*types.Transaction, error)
	// DirectDeposit is a paid mutator transaction binding the contract method 0xec68426f.
	//
	// Solidity: function directDeposit(uint256 _depositID, address who, uint256 amount) returns(bool)
	DirectDeposit(opts *bind.TransactOpts, _depositID *big.Int, who common.Address, amount *big.Int) (*types.Transaction, error)
	// GrantOperator is a paid mutator transaction binding the contract method 0xe348da13.
	//
	// Solidity: function grantOperator(address _operator) returns()
	GrantOperator(opts *bind.TransactOpts, _operator common.Address) (*types.Transaction, error)
	// ReloadRegistry is a paid mutator transaction binding the contract method 0x1476601d.
	//
	// Solidity: function reloadRegistry() returns()
	ReloadRegistry(opts *bind.TransactOpts) (*types.Transaction, error)
	// RevokeOperator is a paid mutator transaction binding the contract method 0xfad8b32a.
	//
	// Solidity: function revokeOperator(address _operator) returns()
	RevokeOperator(opts *bind.TransactOpts, _operator common.Address) (*types.Transaction, error)
	// SetAuthority is a paid mutator transaction binding the contract method 0x7a9e5e4b.
	//
	// Solidity: function setAuthority(address authority_) returns()
	SetAuthority(opts *bind.TransactOpts, authority_ common.Address) (*types.Transaction, error)
	// SetDepositID is a paid mutator transaction binding the contract method 0xda7f7eb7.
	//
	// Solidity: function setDepositID(uint256 _depositID) returns()
	SetDepositID(opts *bind.TransactOpts, _depositID *big.Int) (*types.Transaction, error)
	// SetOwner is a paid mutator transaction binding the contract method 0x13af4035.
	//
	// Solidity: function setOwner(address owner_) returns()
	SetOwner(opts *bind.TransactOpts, owner_ common.Address) (*types.Transaction, error)
	// Start is a paid mutator transaction binding the contract method 0xbe9a6555.
	//
	// Solidity: function start() returns()
	Start(opts *bind.TransactOpts) (*types.Transaction, error)
	// Stop is a paid mutator transaction binding the contract method 0x07da68f5.
	//
	// Solidity: function stop() returns()
	Stop(opts *bind.TransactOpts) (*types.Transaction, error)
}
