// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IEthDkgCaller ...
type IEthDkgCaller interface {
	// TDISPUTEEND is a free data retrieval call binding the contract method 0xd3cf6186.
	//
	// Solidity: function T_DISPUTE_END() view returns(uint256)
	TDISPUTEEND(opts *bind.CallOpts) (*big.Int, error)
	// TDKGCOMPLETE is a free data retrieval call binding the contract method 0x77fbebd1.
	//
	// Solidity: function T_DKG_COMPLETE() view returns(uint256)
	TDKGCOMPLETE(opts *bind.CallOpts) (*big.Int, error)
	// TGPKJDISPUTEEND is a free data retrieval call binding the contract method 0xcc78d245.
	//
	// Solidity: function T_GPKJDISPUTE_END() view returns(uint256)
	TGPKJDISPUTEEND(opts *bind.CallOpts) (*big.Int, error)
	// TGPKJSUBMISSIONEND is a free data retrieval call binding the contract method 0x9c2aa838.
	//
	// Solidity: function T_GPKJ_SUBMISSION_END() view returns(uint256)
	TGPKJSUBMISSIONEND(opts *bind.CallOpts) (*big.Int, error)
	// TKEYSHARESUBMISSIONEND is a free data retrieval call binding the contract method 0xe2291ec3.
	//
	// Solidity: function T_KEY_SHARE_SUBMISSION_END() view returns(uint256)
	TKEYSHARESUBMISSIONEND(opts *bind.CallOpts) (*big.Int, error)
	// TMPKSUBMISSIONEND is a free data retrieval call binding the contract method 0x07f02c54.
	//
	// Solidity: function T_MPK_SUBMISSION_END() view returns(uint256)
	TMPKSUBMISSIONEND(opts *bind.CallOpts) (*big.Int, error)
	// TREGISTRATIONEND is a free data retrieval call binding the contract method 0x0de1553f.
	//
	// Solidity: function T_REGISTRATION_END() view returns(uint256)
	TREGISTRATIONEND(opts *bind.CallOpts) (*big.Int, error)
	// TSHAREDISTRIBUTIONEND is a free data retrieval call binding the contract method 0xdc614e28.
	//
	// Solidity: function T_SHARE_DISTRIBUTION_END() view returns(uint256)
	TSHAREDISTRIBUTIONEND(opts *bind.CallOpts) (*big.Int, error)
	// Addresses is a free data retrieval call binding the contract method 0xedf26d9b.
	//
	// Solidity: function addresses(uint256 idx) view returns(address)
	Addresses(opts *bind.CallOpts, idx *big.Int) (common.Address, error)
	// Commitments1stCoefficient is a free data retrieval call binding the contract method 0x2cf4050b.
	//
	// Solidity: function commitments_1st_coefficient(address addr, uint256 idx) view returns(uint256)
	Commitments1stCoefficient(opts *bind.CallOpts, addr common.Address, idx *big.Int) (*big.Int, error)
	// GetPhaseLength is a free data retrieval call binding the contract method 0x106da57d.
	//
	// Solidity: function getPhaseLength() view returns(uint256)
	GetPhaseLength(opts *bind.CallOpts) (*big.Int, error)
	// GpkjSubmissions is a free data retrieval call binding the contract method 0xfef001a9.
	//
	// Solidity: function gpkj_submissions(address , uint256 ) view returns(uint256)
	GpkjSubmissions(opts *bind.CallOpts, arg0 common.Address, arg1 *big.Int) (*big.Int, error)
	// InitialMessage is a free data retrieval call binding the contract method 0x665f4c81.
	//
	// Solidity: function initialMessage() view returns(bytes)
	InitialMessage(opts *bind.CallOpts) ([]byte, error)
	// InitialSignatures is a free data retrieval call binding the contract method 0xfa055f2f.
	//
	// Solidity: function initialSignatures(address addr, uint256 idx) view returns(uint256)
	InitialSignatures(opts *bind.CallOpts, addr common.Address, idx *big.Int) (*big.Int, error)
	// IsMalicious is a free data retrieval call binding the contract method 0x9c02514a.
	//
	// Solidity: function isMalicious(address addr) view returns(bool)
	IsMalicious(opts *bind.CallOpts, addr common.Address) (bool, error)
	// KeyShares is a free data retrieval call binding the contract method 0x85c02b1d.
	//
	// Solidity: function keyShares(address addr, uint256 idx) view returns(uint256)
	KeyShares(opts *bind.CallOpts, addr common.Address, idx *big.Int) (*big.Int, error)
	// MasterPublicKey is a free data retrieval call binding the contract method 0xe6511378.
	//
	// Solidity: function master_public_key(uint256 ) view returns(uint256)
	MasterPublicKey(opts *bind.CallOpts, arg0 *big.Int) (*big.Int, error)
	// NumberOfRegistrations is a free data retrieval call binding the contract method 0xd8f63eb7.
	//
	// Solidity: function numberOfRegistrations() view returns(uint256)
	NumberOfRegistrations(opts *bind.CallOpts) (*big.Int, error)
	// PublicKeys is a free data retrieval call binding the contract method 0x10782555.
	//
	// Solidity: function publicKeys(address addr, uint256 idx) view returns(uint256)
	PublicKeys(opts *bind.CallOpts, addr common.Address, idx *big.Int) (*big.Int, error)
	// ShareDistributionHashes is a free data retrieval call binding the contract method 0x5634145a.
	//
	// Solidity: function shareDistributionHashes(address addr) view returns(bytes32)
	ShareDistributionHashes(opts *bind.CallOpts, addr common.Address) ([32]byte, error)
	// ValidatorIndex is a free data retrieval call binding the contract method 0x9601ddf9.
	//
	// Solidity: function validatorIndex(address addr) view returns(uint256)
	ValidatorIndex(opts *bind.CallOpts, addr common.Address) (*big.Int, error)
}
