// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

// ITokenTransactor ...
type ITokenTransactor interface {
	// Approve is a paid mutator transaction binding the contract method 0x095ea7b3.
	//
	// Solidity: function approve(address guy, uint256 wad) returns(bool)
	Approve(opts *bind.TransactOpts, guy common.Address, wad *big.Int) (*types.Transaction, error)
	// Approve0 is a paid mutator transaction binding the contract method 0xdaea85c5.
	//
	// Solidity: function approve(address guy) returns(bool)
	Approve0(opts *bind.TransactOpts, guy common.Address) (*types.Transaction, error)
	// Burn is a paid mutator transaction binding the contract method 0x42966c68.
	//
	// Solidity: function burn(uint256 wad) returns()
	Burn(opts *bind.TransactOpts, wad *big.Int) (*types.Transaction, error)
	// Burn0 is a paid mutator transaction binding the contract method 0x9dc29fac.
	//
	// Solidity: function burn(address guy, uint256 wad) returns()
	Burn0(opts *bind.TransactOpts, guy common.Address, wad *big.Int) (*types.Transaction, error)
	// GrantOperator is a paid mutator transaction binding the contract method 0xe348da13.
	//
	// Solidity: function grantOperator(address _operator) returns()
	GrantOperator(opts *bind.TransactOpts, _operator common.Address) (*types.Transaction, error)
	// Mint is a paid mutator transaction binding the contract method 0x40c10f19.
	//
	// Solidity: function mint(address guy, uint256 wad) returns()
	Mint(opts *bind.TransactOpts, guy common.Address, wad *big.Int) (*types.Transaction, error)
	// Mint0 is a paid mutator transaction binding the contract method 0xa0712d68.
	//
	// Solidity: function mint(uint256 wad) returns()
	Mint0(opts *bind.TransactOpts, wad *big.Int) (*types.Transaction, error)
	// Move is a paid mutator transaction binding the contract method 0xbb35783b.
	//
	// Solidity: function move(address src, address dst, uint256 wad) returns()
	Move(opts *bind.TransactOpts, src common.Address, dst common.Address, wad *big.Int) (*types.Transaction, error)
	// Pull is a paid mutator transaction binding the contract method 0xf2d5d56b.
	//
	// Solidity: function pull(address src, uint256 wad) returns()
	Pull(opts *bind.TransactOpts, src common.Address, wad *big.Int) (*types.Transaction, error)
	// Push is a paid mutator transaction binding the contract method 0xb753a98c.
	//
	// Solidity: function push(address dst, uint256 wad) returns()
	Push(opts *bind.TransactOpts, dst common.Address, wad *big.Int) (*types.Transaction, error)
	// RevokeOperator is a paid mutator transaction binding the contract method 0xfad8b32a.
	//
	// Solidity: function revokeOperator(address _operator) returns()
	RevokeOperator(opts *bind.TransactOpts, _operator common.Address) (*types.Transaction, error)
	// SetAuthority is a paid mutator transaction binding the contract method 0x7a9e5e4b.
	//
	// Solidity: function setAuthority(address authority_) returns()
	SetAuthority(opts *bind.TransactOpts, authority_ common.Address) (*types.Transaction, error)
	// SetName is a paid mutator transaction binding the contract method 0x5ac801fe.
	//
	// Solidity: function setName(bytes32 name_) returns()
	SetName(opts *bind.TransactOpts, name_ [32]byte) (*types.Transaction, error)
	// SetOwner is a paid mutator transaction binding the contract method 0x13af4035.
	//
	// Solidity: function setOwner(address owner_) returns()
	SetOwner(opts *bind.TransactOpts, owner_ common.Address) (*types.Transaction, error)
	// Start is a paid mutator transaction binding the contract method 0xbe9a6555.
	//
	// Solidity: function start() returns()
	Start(opts *bind.TransactOpts) (*types.Transaction, error)
	// Stop is a paid mutator transaction binding the contract method 0x07da68f5.
	//
	// Solidity: function stop() returns()
	Stop(opts *bind.TransactOpts) (*types.Transaction, error)
	// Transfer is a paid mutator transaction binding the contract method 0xa9059cbb.
	//
	// Solidity: function transfer(address dst, uint256 wad) returns(bool)
	Transfer(opts *bind.TransactOpts, dst common.Address, wad *big.Int) (*types.Transaction, error)
	// TransferFrom is a paid mutator transaction binding the contract method 0x23b872dd.
	//
	// Solidity: function transferFrom(address src, address dst, uint256 wad) returns(bool)
	TransferFrom(opts *bind.TransactOpts, src common.Address, dst common.Address, wad *big.Int) (*types.Transaction, error)
}
