// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IValidatorsCaller ...
type IValidatorsCaller interface {
	// BalanceReward is a free data retrieval call binding the contract method 0x9fb69b43.
	//
	// Solidity: function balanceReward() view returns(uint256)
	BalanceReward(opts *bind.CallOpts) (*big.Int, error)
	// BalanceRewardFor is a free data retrieval call binding the contract method 0x9be5d83e.
	//
	// Solidity: function balanceRewardFor(address who) view returns(uint256)
	BalanceRewardFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// BalanceStake is a free data retrieval call binding the contract method 0x8aa2799c.
	//
	// Solidity: function balanceStake() view returns(uint256)
	BalanceStake(opts *bind.CallOpts) (*big.Int, error)
	// BalanceStakeFor is a free data retrieval call binding the contract method 0x35ba4daf.
	//
	// Solidity: function balanceStakeFor(address who) view returns(uint256)
	BalanceStakeFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// BalanceUnlocked is a free data retrieval call binding the contract method 0x5b6a0d1e.
	//
	// Solidity: function balanceUnlocked() view returns(uint256)
	BalanceUnlocked(opts *bind.CallOpts) (*big.Int, error)
	// BalanceUnlockedFor is a free data retrieval call binding the contract method 0x2e713306.
	//
	// Solidity: function balanceUnlockedFor(address who) view returns(uint256)
	BalanceUnlockedFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// BalanceUnlockedReward is a free data retrieval call binding the contract method 0xc328b464.
	//
	// Solidity: function balanceUnlockedReward() view returns(uint256)
	BalanceUnlockedReward(opts *bind.CallOpts) (*big.Int, error)
	// BalanceUnlockedRewardFor is a free data retrieval call binding the contract method 0x515c31a1.
	//
	// Solidity: function balanceUnlockedRewardFor(address who) view returns(uint256)
	BalanceUnlockedRewardFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// Epoch is a free data retrieval call binding the contract method 0x900cf0cf.
	//
	// Solidity: function epoch() view returns(uint256)
	Epoch(opts *bind.CallOpts) (*big.Int, error)
	// ExtractUint256 is a free data retrieval call binding the contract method 0x1c8c8ba4.
	//
	// Solidity: function extractUint256(bytes src, uint256 offset) pure returns(uint256 val)
	ExtractUint256(opts *bind.CallOpts, src []byte, offset *big.Int) (*big.Int, error)
	// ExtractUint32 is a free data retrieval call binding the contract method 0xc1312f4d.
	//
	// Solidity: function extractUint32(bytes src, uint256 idx) pure returns(uint32 val)
	ExtractUint32(opts *bind.CallOpts, src []byte, idx *big.Int) (uint32, error)
	// GetChainId is a free data retrieval call binding the contract method 0x3408e470.
	//
	// Solidity: function getChainId() view returns(uint32)
	GetChainId(opts *bind.CallOpts) (uint32, error)
	// GetChainIdFromSnapshot is a free data retrieval call binding the contract method 0x19f74669.
	//
	// Solidity: function getChainIdFromSnapshot(uint256 snapshotNumber) view returns(uint32)
	GetChainIdFromSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) (uint32, error)
	// GetHeightFromSnapshot is a free data retrieval call binding the contract method 0xe380b228.
	//
	// Solidity: function getHeightFromSnapshot(uint256 snapshotNumber) view returns(uint32)
	GetHeightFromSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) (uint32, error)
	// GetMadHeightFromSnapshot is a free data retrieval call binding the contract method 0x4f4ea614.
	//
	// Solidity: function getMadHeightFromSnapshot(uint256 snapshotNumber) view returns(uint32)
	GetMadHeightFromSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) (uint32, error)
	// GetRawBlockClaimsSnapshot is a free data retrieval call binding the contract method 0x6372fe51.
	//
	// Solidity: function getRawBlockClaimsSnapshot(uint256 snapshotNumber) view returns(bytes)
	GetRawBlockClaimsSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) ([]byte, error)
	// GetRawSignatureSnapshot is a free data retrieval call binding the contract method 0x35b6c632.
	//
	// Solidity: function getRawSignatureSnapshot(uint256 snapshotNumber) view returns(bytes)
	GetRawSignatureSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) ([]byte, error)
	// GetValidatorPublicKey is a free data retrieval call binding the contract method 0x4e6f4a22.
	//
	// Solidity: function getValidatorPublicKey(address _validator) view returns(uint256[2])
	GetValidatorPublicKey(opts *bind.CallOpts, _validator common.Address) ([2]*big.Int, error)
	// GetValidators is a free data retrieval call binding the contract method 0xb7ab4db5.
	//
	// Solidity: function getValidators() view returns(address[])
	GetValidators(opts *bind.CallOpts) ([]common.Address, error)
	// IsValidator is a free data retrieval call binding the contract method 0xfacd743b.
	//
	// Solidity: function isValidator(address validator) view returns(bool)
	IsValidator(opts *bind.CallOpts, validator common.Address) (bool, error)
	// MajorStakeFine is a free data retrieval call binding the contract method 0xad43d845.
	//
	// Solidity: function majorStakeFine() view returns(uint256)
	MajorStakeFine(opts *bind.CallOpts) (*big.Int, error)
	// MinEthSnapshotSize is a free data retrieval call binding the contract method 0xe4b82105.
	//
	// Solidity: function minEthSnapshotSize() view returns(uint256)
	MinEthSnapshotSize(opts *bind.CallOpts) (*big.Int, error)
	// MinMadSnapshotSize is a free data retrieval call binding the contract method 0xc17cb9ee.
	//
	// Solidity: function minMadSnapshotSize() view returns(uint256)
	MinMadSnapshotSize(opts *bind.CallOpts) (*big.Int, error)
	// MinimumStake is a free data retrieval call binding the contract method 0xec5ffac2.
	//
	// Solidity: function minimumStake() view returns(uint256)
	MinimumStake(opts *bind.CallOpts) (*big.Int, error)
	// MinorStakeFine is a free data retrieval call binding the contract method 0x6d059126.
	//
	// Solidity: function minorStakeFine() view returns(uint256)
	MinorStakeFine(opts *bind.CallOpts) (*big.Int, error)
	// ParseSignatureGroup is a free data retrieval call binding the contract method 0x9be2f2df.
	//
	// Solidity: function parseSignatureGroup(bytes _signatureGroup) pure returns(uint256[4] publicKey, uint256[2] signature)
	ParseSignatureGroup(opts *bind.CallOpts, _signatureGroup []byte) (struct {
		PublicKey [4]*big.Int
		Signature [2]*big.Int
	}, error)
	// Reverse is a free data retrieval call binding the contract method 0xec11c823.
	//
	// Solidity: function reverse(bytes orig) pure returns(bytes reversed)
	Reverse(opts *bind.CallOpts, orig []byte) ([]byte, error)
	// RewardAmount is a free data retrieval call binding the contract method 0xf7b2a7be.
	//
	// Solidity: function rewardAmount() view returns(uint256)
	RewardAmount(opts *bind.CallOpts) (*big.Int, error)
	// RewardBonus is a free data retrieval call binding the contract method 0xfdf553cf.
	//
	// Solidity: function rewardBonus() view returns(uint256)
	RewardBonus(opts *bind.CallOpts) (*big.Int, error)
	// SnapshotDesperationDelay is a free data retrieval call binding the contract method 0x6b797156.
	//
	// Solidity: function snapshotDesperationDelay() view returns(uint256)
	SnapshotDesperationDelay(opts *bind.CallOpts) (*big.Int, error)
	// SnapshotDesperationFactor is a free data retrieval call binding the contract method 0xfcf96652.
	//
	// Solidity: function snapshotDesperationFactor() view returns(uint256)
	SnapshotDesperationFactor(opts *bind.CallOpts) (*big.Int, error)
}
