// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/core/types"
)

// IAccusationTransactor ...
type IAccusationTransactor interface {
	// AccuseInvalidTransactionConsumption is a paid mutator transaction binding the contract method 0xcac6a5f0.
	//
	// Solidity: function AccuseInvalidTransactionConsumption(bytes _pClaims, bytes _pClaimsSig, bytes _bClaims, bytes _bClaimsSigGroup, bytes _txInPreImage, bytes[3] _proofs) returns()
	AccuseInvalidTransactionConsumption(opts *bind.TransactOpts, _pClaims []byte, _pClaimsSig []byte, _bClaims []byte, _bClaimsSigGroup []byte, _txInPreImage []byte, _proofs [3][]byte) (*types.Transaction, error)
	// AccuseMultipleProposal is a paid mutator transaction binding the contract method 0x7f321b2d.
	//
	// Solidity: function AccuseMultipleProposal(bytes _signature0, bytes _pClaims0, bytes _signature1, bytes _pClaims1) returns()
	AccuseMultipleProposal(opts *bind.TransactOpts, _signature0 []byte, _pClaims0 []byte, _signature1 []byte, _pClaims1 []byte) (*types.Transaction, error)
}
