// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IRegistryCaller ...
type IRegistryCaller interface {
	// Lookup is a free data retrieval call binding the contract method 0xf67187ac.
	//
	// Solidity: function lookup(string name) view returns(address)
	Lookup(opts *bind.CallOpts, name string) (common.Address, error)
}
