// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

// IParticipantsTransactor ...
type IParticipantsTransactor interface {
	// AddValidator is a paid mutator transaction binding the contract method 0xeb6320c7.
	//
	// Solidity: function addValidator(address _validator, uint256[2] _madID) returns(uint8)
	AddValidator(opts *bind.TransactOpts, _validator common.Address, _madID [2]*big.Int) (*types.Transaction, error)
	// ConfirmValidators is a paid mutator transaction binding the contract method 0x35c6a163.
	//
	// Solidity: function confirmValidators() returns(bool)
	ConfirmValidators(opts *bind.TransactOpts) (*types.Transaction, error)
	// InitializeParticipants is a paid mutator transaction binding the contract method 0xee8420dd.
	//
	// Solidity: function initializeParticipants(address registry) returns()
	InitializeParticipants(opts *bind.TransactOpts, registry common.Address) (*types.Transaction, error)
	// RemoveValidator is a paid mutator transaction binding the contract method 0x844469b2.
	//
	// Solidity: function removeValidator(address _validator, uint256[2] _madID) returns(uint8)
	RemoveValidator(opts *bind.TransactOpts, _validator common.Address, _madID [2]*big.Int) (*types.Transaction, error)
	// SetChainId is a paid mutator transaction binding the contract method 0xa179f124.
	//
	// Solidity: function setChainId(uint32 _chainId) returns()
	SetChainId(opts *bind.TransactOpts, _chainId uint32) (*types.Transaction, error)
	// SetValidatorMaxCount is a paid mutator transaction binding the contract method 0x2cab37f7.
	//
	// Solidity: function setValidatorMaxCount(uint8 max) returns()
	SetValidatorMaxCount(opts *bind.TransactOpts, max uint8) (*types.Transaction, error)
	// ValidatorCount is a paid mutator transaction binding the contract method 0x0f43a677.
	//
	// Solidity: function validatorCount() returns(uint8)
	ValidatorCount(opts *bind.TransactOpts) (*types.Transaction, error)
	// ValidatorMaxCount is a paid mutator transaction binding the contract method 0x09f0d45d.
	//
	// Solidity: function validatorMaxCount() returns(uint8)
	ValidatorMaxCount(opts *bind.TransactOpts) (*types.Transaction, error)
}
