// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// ITokenCaller ...
type ITokenCaller interface {
	// Allowance is a free data retrieval call binding the contract method 0xdd62ed3e.
	//
	// Solidity: function allowance(address , address ) view returns(uint256)
	Allowance(opts *bind.CallOpts, arg0 common.Address, arg1 common.Address) (*big.Int, error)
	// Authority is a free data retrieval call binding the contract method 0xbf7e214f.
	//
	// Solidity: function authority() view returns(address)
	Authority(opts *bind.CallOpts) (common.Address, error)
	// BalanceOf is a free data retrieval call binding the contract method 0x70a08231.
	//
	// Solidity: function balanceOf(address ) view returns(uint256)
	BalanceOf(opts *bind.CallOpts, arg0 common.Address) (*big.Int, error)
	// Decimals is a free data retrieval call binding the contract method 0x313ce567.
	//
	// Solidity: function decimals() view returns(uint256)
	Decimals(opts *bind.CallOpts) (*big.Int, error)
	// Name is a free data retrieval call binding the contract method 0x06fdde03.
	//
	// Solidity: function name() view returns(bytes32)
	Name(opts *bind.CallOpts) ([32]byte, error)
	// Owner is a free data retrieval call binding the contract method 0x8da5cb5b.
	//
	// Solidity: function owner() view returns(address)
	Owner(opts *bind.CallOpts) (common.Address, error)
	// Stopped is a free data retrieval call binding the contract method 0x75f12b21.
	//
	// Solidity: function stopped() view returns(bool)
	Stopped(opts *bind.CallOpts) (bool, error)
	// Symbol is a free data retrieval call binding the contract method 0x95d89b41.
	//
	// Solidity: function symbol() view returns(bytes32)
	Symbol(opts *bind.CallOpts) ([32]byte, error)
	// TotalSupply is a free data retrieval call binding the contract method 0x18160ddd.
	//
	// Solidity: function totalSupply() view returns(uint256)
	TotalSupply(opts *bind.CallOpts) (*big.Int, error)
}
