// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

// IRegistryTransactor ...
type IRegistryTransactor interface {
	// GrantOperator is a paid mutator transaction binding the contract method 0xe348da13.
	//
	// Solidity: function grantOperator(address _operator) returns()
	GrantOperator(opts *bind.TransactOpts, _operator common.Address) (*types.Transaction, error)
	// Register is a paid mutator transaction binding the contract method 0x1e59c529.
	//
	// Solidity: function register(string name, address dst) returns()
	Register(opts *bind.TransactOpts, name string, dst common.Address) (*types.Transaction, error)
	// Remove is a paid mutator transaction binding the contract method 0x80599e4b.
	//
	// Solidity: function remove(string name) returns()
	Remove(opts *bind.TransactOpts, name string) (*types.Transaction, error)
	// RevokeOperator is a paid mutator transaction binding the contract method 0xfad8b32a.
	//
	// Solidity: function revokeOperator(address _operator) returns()
	RevokeOperator(opts *bind.TransactOpts, _operator common.Address) (*types.Transaction, error)
}
