// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IParticipantsCaller ...
type IParticipantsCaller interface {
	// GetChainId is a free data retrieval call binding the contract method 0x3408e470.
	//
	// Solidity: function getChainId() view returns(uint32)
	GetChainId(opts *bind.CallOpts) (uint32, error)
	// GetValidatorPublicKey is a free data retrieval call binding the contract method 0x4e6f4a22.
	//
	// Solidity: function getValidatorPublicKey(address _validator) view returns(uint256[2])
	GetValidatorPublicKey(opts *bind.CallOpts, _validator common.Address) ([2]*big.Int, error)
	// GetValidators is a free data retrieval call binding the contract method 0xb7ab4db5.
	//
	// Solidity: function getValidators() view returns(address[])
	GetValidators(opts *bind.CallOpts) ([]common.Address, error)
	// IsValidator is a free data retrieval call binding the contract method 0xfacd743b.
	//
	// Solidity: function isValidator(address validator) view returns(bool)
	IsValidator(opts *bind.CallOpts, validator common.Address) (bool, error)
}
