// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IDepositCaller ...
type IDepositCaller interface {
	// Authority is a free data retrieval call binding the contract method 0xbf7e214f.
	//
	// Solidity: function authority() view returns(address)
	Authority(opts *bind.CallOpts) (common.Address, error)
	// DepositID is a free data retrieval call binding the contract method 0xb3117446.
	//
	// Solidity: function depositID() view returns(uint256)
	DepositID(opts *bind.CallOpts) (*big.Int, error)
	// Deposits is a free data retrieval call binding the contract method 0xb02c43d0.
	//
	// Solidity: function deposits(uint256 _depositID) view returns(uint256)
	Deposits(opts *bind.CallOpts, _depositID *big.Int) (*big.Int, error)
	// Owner is a free data retrieval call binding the contract method 0x8da5cb5b.
	//
	// Solidity: function owner() view returns(address)
	Owner(opts *bind.CallOpts) (common.Address, error)
	// Stopped is a free data retrieval call binding the contract method 0x75f12b21.
	//
	// Solidity: function stopped() view returns(bool)
	Stopped(opts *bind.CallOpts) (bool, error)
	// TotalDeposited is a free data retrieval call binding the contract method 0xff50abdc.
	//
	// Solidity: function totalDeposited() view returns(uint256)
	TotalDeposited(opts *bind.CallOpts) (*big.Int, error)
}
