// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// IParticipantsFilterer ...
type IParticipantsFilterer interface {
	// FilterValidatorCreated is a free log retrieval operation binding the contract event 0xef5e89a9416c26e0a0a37c1f630958c8c88d9efad59f553f94cff0bed0a268d3.
	//
	// Solidity: event ValidatorCreated(address indexed validator, address indexed signer, uint256[2] madID)
	FilterValidatorCreated(opts *bind.FilterOpts, validator []common.Address, signer []common.Address) (*ParticipantsValidatorCreatedIterator, error)
	// WatchValidatorCreated is a free log subscription operation binding the contract event 0xef5e89a9416c26e0a0a37c1f630958c8c88d9efad59f553f94cff0bed0a268d3.
	//
	// Solidity: event ValidatorCreated(address indexed validator, address indexed signer, uint256[2] madID)
	WatchValidatorCreated(opts *bind.WatchOpts, sink chan<- *ParticipantsValidatorCreated, validator []common.Address, signer []common.Address) (event.Subscription, error)
	// ParseValidatorCreated is a log parse operation binding the contract event 0xef5e89a9416c26e0a0a37c1f630958c8c88d9efad59f553f94cff0bed0a268d3.
	//
	// Solidity: event ValidatorCreated(address indexed validator, address indexed signer, uint256[2] madID)
	ParseValidatorCreated(log types.Log) (*ParticipantsValidatorCreated, error)
	// FilterValidatorJoined is a free log retrieval operation binding the contract event 0x8c25e214c5693ebaf8008875bacedeb9e0aafd393864a314ed1801b2a4e13dd9.
	//
	// Solidity: event ValidatorJoined(address indexed validator, uint256[2] madID)
	FilterValidatorJoined(opts *bind.FilterOpts, validator []common.Address) (*ParticipantsValidatorJoinedIterator, error)
	// WatchValidatorJoined is a free log subscription operation binding the contract event 0x8c25e214c5693ebaf8008875bacedeb9e0aafd393864a314ed1801b2a4e13dd9.
	//
	// Solidity: event ValidatorJoined(address indexed validator, uint256[2] madID)
	WatchValidatorJoined(opts *bind.WatchOpts, sink chan<- *ParticipantsValidatorJoined, validator []common.Address) (event.Subscription, error)
	// ParseValidatorJoined is a log parse operation binding the contract event 0x8c25e214c5693ebaf8008875bacedeb9e0aafd393864a314ed1801b2a4e13dd9.
	//
	// Solidity: event ValidatorJoined(address indexed validator, uint256[2] madID)
	ParseValidatorJoined(log types.Log) (*ParticipantsValidatorJoined, error)
	// FilterValidatorLeft is a free log retrieval operation binding the contract event 0x319bbadb03b94aedc69babb34a28675536a9cb30f4bbde343e1d0018c44ebd94.
	//
	// Solidity: event ValidatorLeft(address indexed validator, uint256[2] pkHash)
	FilterValidatorLeft(opts *bind.FilterOpts, validator []common.Address) (*ParticipantsValidatorLeftIterator, error)
	// WatchValidatorLeft is a free log subscription operation binding the contract event 0x319bbadb03b94aedc69babb34a28675536a9cb30f4bbde343e1d0018c44ebd94.
	//
	// Solidity: event ValidatorLeft(address indexed validator, uint256[2] pkHash)
	WatchValidatorLeft(opts *bind.WatchOpts, sink chan<- *ParticipantsValidatorLeft, validator []common.Address) (event.Subscription, error)
	// ParseValidatorLeft is a log parse operation binding the contract event 0x319bbadb03b94aedc69babb34a28675536a9cb30f4bbde343e1d0018c44ebd94.
	//
	// Solidity: event ValidatorLeft(address indexed validator, uint256[2] pkHash)
	ParseValidatorLeft(log types.Log) (*ParticipantsValidatorLeft, error)
	// FilterValidatorQueued is a free log retrieval operation binding the contract event 0xb4389eb1c66b46169245bc8c147e4b13a2b88adcaa44d001b0fadf25890b773d.
	//
	// Solidity: event ValidatorQueued(address indexed validator, uint256[2] pkHash)
	FilterValidatorQueued(opts *bind.FilterOpts, validator []common.Address) (*ParticipantsValidatorQueuedIterator, error)
	// WatchValidatorQueued is a free log subscription operation binding the contract event 0xb4389eb1c66b46169245bc8c147e4b13a2b88adcaa44d001b0fadf25890b773d.
	//
	// Solidity: event ValidatorQueued(address indexed validator, uint256[2] pkHash)
	WatchValidatorQueued(opts *bind.WatchOpts, sink chan<- *ParticipantsValidatorQueued, validator []common.Address) (event.Subscription, error)
	// ParseValidatorQueued is a log parse operation binding the contract event 0xb4389eb1c66b46169245bc8c147e4b13a2b88adcaa44d001b0fadf25890b773d.
	//
	// Solidity: event ValidatorQueued(address indexed validator, uint256[2] pkHash)
	ParseValidatorQueued(log types.Log) (*ParticipantsValidatorQueued, error)
}
