// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
)

// ISnapshotsCaller ...
type ISnapshotsCaller interface {
	// Epoch is a free data retrieval call binding the contract method 0x900cf0cf.
	//
	// Solidity: function epoch() view returns(uint256)
	Epoch(opts *bind.CallOpts) (*big.Int, error)
	// ExtractUint256 is a free data retrieval call binding the contract method 0x1c8c8ba4.
	//
	// Solidity: function extractUint256(bytes src, uint256 offset) pure returns(uint256 val)
	ExtractUint256(opts *bind.CallOpts, src []byte, offset *big.Int) (*big.Int, error)
	// ExtractUint32 is a free data retrieval call binding the contract method 0xc1312f4d.
	//
	// Solidity: function extractUint32(bytes src, uint256 idx) pure returns(uint32 val)
	ExtractUint32(opts *bind.CallOpts, src []byte, idx *big.Int) (uint32, error)
	// GetChainIdFromSnapshot is a free data retrieval call binding the contract method 0x19f74669.
	//
	// Solidity: function getChainIdFromSnapshot(uint256 snapshotNumber) view returns(uint32)
	GetChainIdFromSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) (uint32, error)
	// GetHeightFromSnapshot is a free data retrieval call binding the contract method 0xe380b228.
	//
	// Solidity: function getHeightFromSnapshot(uint256 snapshotNumber) view returns(uint32)
	GetHeightFromSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) (uint32, error)
	// GetMadHeightFromSnapshot is a free data retrieval call binding the contract method 0x4f4ea614.
	//
	// Solidity: function getMadHeightFromSnapshot(uint256 snapshotNumber) view returns(uint32)
	GetMadHeightFromSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) (uint32, error)
	// GetRawBlockClaimsSnapshot is a free data retrieval call binding the contract method 0x6372fe51.
	//
	// Solidity: function getRawBlockClaimsSnapshot(uint256 snapshotNumber) view returns(bytes)
	GetRawBlockClaimsSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) ([]byte, error)
	// GetRawSignatureSnapshot is a free data retrieval call binding the contract method 0x35b6c632.
	//
	// Solidity: function getRawSignatureSnapshot(uint256 snapshotNumber) view returns(bytes)
	GetRawSignatureSnapshot(opts *bind.CallOpts, snapshotNumber *big.Int) ([]byte, error)
	// MinEthSnapshotSize is a free data retrieval call binding the contract method 0xe4b82105.
	//
	// Solidity: function minEthSnapshotSize() view returns(uint256)
	MinEthSnapshotSize(opts *bind.CallOpts) (*big.Int, error)
	// MinMadSnapshotSize is a free data retrieval call binding the contract method 0xc17cb9ee.
	//
	// Solidity: function minMadSnapshotSize() view returns(uint256)
	MinMadSnapshotSize(opts *bind.CallOpts) (*big.Int, error)
	// ParseSignatureGroup is a free data retrieval call binding the contract method 0x9be2f2df.
	//
	// Solidity: function parseSignatureGroup(bytes _signatureGroup) pure returns(uint256[4] publicKey, uint256[2] signature)
	ParseSignatureGroup(opts *bind.CallOpts, _signatureGroup []byte) (struct {
		PublicKey [4]*big.Int
		Signature [2]*big.Int
	}, error)
	// Reverse is a free data retrieval call binding the contract method 0xec11c823.
	//
	// Solidity: function reverse(bytes orig) pure returns(bytes reversed)
	Reverse(opts *bind.CallOpts, orig []byte) ([]byte, error)
	// SnapshotDesperationDelay is a free data retrieval call binding the contract method 0x6b797156.
	//
	// Solidity: function snapshotDesperationDelay() view returns(uint256)
	SnapshotDesperationDelay(opts *bind.CallOpts) (*big.Int, error)
	// SnapshotDesperationFactor is a free data retrieval call binding the contract method 0xfcf96652.
	//
	// Solidity: function snapshotDesperationFactor() view returns(uint256)
	SnapshotDesperationFactor(opts *bind.CallOpts) (*big.Int, error)
}
