// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IStakingCaller ...
type IStakingCaller interface {
	// BalanceReward is a free data retrieval call binding the contract method 0x9fb69b43.
	//
	// Solidity: function balanceReward() view returns(uint256)
	BalanceReward(opts *bind.CallOpts) (*big.Int, error)
	// BalanceRewardFor is a free data retrieval call binding the contract method 0x9be5d83e.
	//
	// Solidity: function balanceRewardFor(address who) view returns(uint256)
	BalanceRewardFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// BalanceStake is a free data retrieval call binding the contract method 0x8aa2799c.
	//
	// Solidity: function balanceStake() view returns(uint256)
	BalanceStake(opts *bind.CallOpts) (*big.Int, error)
	// BalanceStakeFor is a free data retrieval call binding the contract method 0x35ba4daf.
	//
	// Solidity: function balanceStakeFor(address who) view returns(uint256)
	BalanceStakeFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// BalanceUnlocked is a free data retrieval call binding the contract method 0x5b6a0d1e.
	//
	// Solidity: function balanceUnlocked() view returns(uint256)
	BalanceUnlocked(opts *bind.CallOpts) (*big.Int, error)
	// BalanceUnlockedFor is a free data retrieval call binding the contract method 0x2e713306.
	//
	// Solidity: function balanceUnlockedFor(address who) view returns(uint256)
	BalanceUnlockedFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// BalanceUnlockedReward is a free data retrieval call binding the contract method 0xc328b464.
	//
	// Solidity: function balanceUnlockedReward() view returns(uint256)
	BalanceUnlockedReward(opts *bind.CallOpts) (*big.Int, error)
	// BalanceUnlockedRewardFor is a free data retrieval call binding the contract method 0x515c31a1.
	//
	// Solidity: function balanceUnlockedRewardFor(address who) view returns(uint256)
	BalanceUnlockedRewardFor(opts *bind.CallOpts, who common.Address) (*big.Int, error)
	// MajorStakeFine is a free data retrieval call binding the contract method 0xad43d845.
	//
	// Solidity: function majorStakeFine() view returns(uint256)
	MajorStakeFine(opts *bind.CallOpts) (*big.Int, error)
	// MinimumStake is a free data retrieval call binding the contract method 0xec5ffac2.
	//
	// Solidity: function minimumStake() view returns(uint256)
	MinimumStake(opts *bind.CallOpts) (*big.Int, error)
	// MinorStakeFine is a free data retrieval call binding the contract method 0x6d059126.
	//
	// Solidity: function minorStakeFine() view returns(uint256)
	MinorStakeFine(opts *bind.CallOpts) (*big.Int, error)
	// RewardAmount is a free data retrieval call binding the contract method 0xf7b2a7be.
	//
	// Solidity: function rewardAmount() view returns(uint256)
	RewardAmount(opts *bind.CallOpts) (*big.Int, error)
	// RewardBonus is a free data retrieval call binding the contract method 0xfdf553cf.
	//
	// Solidity: function rewardBonus() view returns(uint256)
	RewardBonus(opts *bind.CallOpts) (*big.Int, error)
}
