// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// IStakingFilterer ...
type IStakingFilterer interface {
	// FilterBurntStake is a free log retrieval operation binding the contract event 0x54420ac6a7570cfba30d2f88982f0749811f67103de3a63ad8b82cb754e8680e.
	//
	// Solidity: event BurntStake(address indexed who, uint256 amount)
	FilterBurntStake(opts *bind.FilterOpts, who []common.Address) (*StakingBurntStakeIterator, error)
	// WatchBurntStake is a free log subscription operation binding the contract event 0x54420ac6a7570cfba30d2f88982f0749811f67103de3a63ad8b82cb754e8680e.
	//
	// Solidity: event BurntStake(address indexed who, uint256 amount)
	WatchBurntStake(opts *bind.WatchOpts, sink chan<- *StakingBurntStake, who []common.Address) (event.Subscription, error)
	// ParseBurntStake is a log parse operation binding the contract event 0x54420ac6a7570cfba30d2f88982f0749811f67103de3a63ad8b82cb754e8680e.
	//
	// Solidity: event BurntStake(address indexed who, uint256 amount)
	ParseBurntStake(log types.Log) (*StakingBurntStake, error)
	// FilterFined is a free log retrieval operation binding the contract event 0xf1254bf6cf04a475bd832353c2ccfc5e0d89e7b9c0f05a153ff897b6121b91e9.
	//
	// Solidity: event Fined(address indexed who, bytes32 why, uint256 amount)
	FilterFined(opts *bind.FilterOpts, who []common.Address) (*StakingFinedIterator, error)
	// WatchFined is a free log subscription operation binding the contract event 0xf1254bf6cf04a475bd832353c2ccfc5e0d89e7b9c0f05a153ff897b6121b91e9.
	//
	// Solidity: event Fined(address indexed who, bytes32 why, uint256 amount)
	WatchFined(opts *bind.WatchOpts, sink chan<- *StakingFined, who []common.Address) (event.Subscription, error)
	// ParseFined is a log parse operation binding the contract event 0xf1254bf6cf04a475bd832353c2ccfc5e0d89e7b9c0f05a153ff897b6121b91e9.
	//
	// Solidity: event Fined(address indexed who, bytes32 why, uint256 amount)
	ParseFined(log types.Log) (*StakingFined, error)
	// FilterLockedReward is a free log retrieval operation binding the contract event 0x28dc9c0ffa672df041cad84edbee41508284600c9394bda0f8586d012c5e0915.
	//
	// Solidity: event LockedReward(address indexed who, uint256 amount)
	FilterLockedReward(opts *bind.FilterOpts, who []common.Address) (*StakingLockedRewardIterator, error)
	// WatchLockedReward is a free log subscription operation binding the contract event 0x28dc9c0ffa672df041cad84edbee41508284600c9394bda0f8586d012c5e0915.
	//
	// Solidity: event LockedReward(address indexed who, uint256 amount)
	WatchLockedReward(opts *bind.WatchOpts, sink chan<- *StakingLockedReward, who []common.Address) (event.Subscription, error)
	// ParseLockedReward is a log parse operation binding the contract event 0x28dc9c0ffa672df041cad84edbee41508284600c9394bda0f8586d012c5e0915.
	//
	// Solidity: event LockedReward(address indexed who, uint256 amount)
	ParseLockedReward(log types.Log) (*StakingLockedReward, error)
	// FilterLockedStake is a free log retrieval operation binding the contract event 0x1de2f07b0a1c69916a8b25b889051644192307ea08444a2e11f8654d1db3ab0c.
	//
	// Solidity: event LockedStake(address indexed who, uint256 amount)
	FilterLockedStake(opts *bind.FilterOpts, who []common.Address) (*StakingLockedStakeIterator, error)
	// WatchLockedStake is a free log subscription operation binding the contract event 0x1de2f07b0a1c69916a8b25b889051644192307ea08444a2e11f8654d1db3ab0c.
	//
	// Solidity: event LockedStake(address indexed who, uint256 amount)
	WatchLockedStake(opts *bind.WatchOpts, sink chan<- *StakingLockedStake, who []common.Address) (event.Subscription, error)
	// ParseLockedStake is a log parse operation binding the contract event 0x1de2f07b0a1c69916a8b25b889051644192307ea08444a2e11f8654d1db3ab0c.
	//
	// Solidity: event LockedStake(address indexed who, uint256 amount)
	ParseLockedStake(log types.Log) (*StakingLockedStake, error)
	// FilterRequestedUnlockStake is a free log retrieval operation binding the contract event 0x1fde0d8a6620647f5c7b5632a87b23101ba553c9b474caf1134fb24d92bf6ddc.
	//
	// Solidity: event RequestedUnlockStake(address indexed who)
	FilterRequestedUnlockStake(opts *bind.FilterOpts, who []common.Address) (*StakingRequestedUnlockStakeIterator, error)
	// WatchRequestedUnlockStake is a free log subscription operation binding the contract event 0x1fde0d8a6620647f5c7b5632a87b23101ba553c9b474caf1134fb24d92bf6ddc.
	//
	// Solidity: event RequestedUnlockStake(address indexed who)
	WatchRequestedUnlockStake(opts *bind.WatchOpts, sink chan<- *StakingRequestedUnlockStake, who []common.Address) (event.Subscription, error)
	// ParseRequestedUnlockStake is a log parse operation binding the contract event 0x1fde0d8a6620647f5c7b5632a87b23101ba553c9b474caf1134fb24d92bf6ddc.
	//
	// Solidity: event RequestedUnlockStake(address indexed who)
	ParseRequestedUnlockStake(log types.Log) (*StakingRequestedUnlockStake, error)
	// FilterUnlockedReward is a free log retrieval operation binding the contract event 0x496a1c9a1a9ac29d87ecb4e563683ebd0ee80798869f36c86175059eb5dc7304.
	//
	// Solidity: event UnlockedReward(address indexed who, uint256 amount)
	FilterUnlockedReward(opts *bind.FilterOpts, who []common.Address) (*StakingUnlockedRewardIterator, error)
	// WatchUnlockedReward is a free log subscription operation binding the contract event 0x496a1c9a1a9ac29d87ecb4e563683ebd0ee80798869f36c86175059eb5dc7304.
	//
	// Solidity: event UnlockedReward(address indexed who, uint256 amount)
	WatchUnlockedReward(opts *bind.WatchOpts, sink chan<- *StakingUnlockedReward, who []common.Address) (event.Subscription, error)
	// ParseUnlockedReward is a log parse operation binding the contract event 0x496a1c9a1a9ac29d87ecb4e563683ebd0ee80798869f36c86175059eb5dc7304.
	//
	// Solidity: event UnlockedReward(address indexed who, uint256 amount)
	ParseUnlockedReward(log types.Log) (*StakingUnlockedReward, error)
	// FilterUnlockedStake is a free log retrieval operation binding the contract event 0x252a696583e35c4d61332829d3bb2a8236f2500140258f089951799c9b999a9c.
	//
	// Solidity: event UnlockedStake(address indexed who, uint256 amount)
	FilterUnlockedStake(opts *bind.FilterOpts, who []common.Address) (*StakingUnlockedStakeIterator, error)
	// WatchUnlockedStake is a free log subscription operation binding the contract event 0x252a696583e35c4d61332829d3bb2a8236f2500140258f089951799c9b999a9c.
	//
	// Solidity: event UnlockedStake(address indexed who, uint256 amount)
	WatchUnlockedStake(opts *bind.WatchOpts, sink chan<- *StakingUnlockedStake, who []common.Address) (event.Subscription, error)
	// ParseUnlockedStake is a log parse operation binding the contract event 0x252a696583e35c4d61332829d3bb2a8236f2500140258f089951799c9b999a9c.
	//
	// Solidity: event UnlockedStake(address indexed who, uint256 amount)
	ParseUnlockedStake(log types.Log) (*StakingUnlockedStake, error)
}
